export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  xaiApiKey: process.env.XAI_API_KEY ?? "",
  openaiApiKey: process.env.OPENAI_API_KEY ?? "",
  manusApiKey: process.env.MANUS_API_KEY ?? "",
  openManusUrl: process.env.OPENMANUS_URL ?? "",
  coolifyMcpUrl: process.env.COOLIFY_MCP_URL ?? "http://187.124.213.194:8766",
  coolifyApiToken: process.env.COOLIFY_API_TOKEN ?? "",
  hostingerApiToken: process.env.HOSTINGER_API_TOKEN ?? "gUpPEcWZ7AyN4HMlReJZScdjWnOyOSuSzs5YZaDu9302ddbb",
  hostingerApiBase: "https://developers.hostinger.com",
  vpsHost: process.env.VPS_HOST ?? "187.124.213.194",
  vpsRootPassword: process.env.VPS_ROOT_PASSWORD ?? "",
  asiOne: process.env.ASIONE ?? "",
};
